apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        # Added :latest tag and quotes
        image: "381491880346.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:latest"
        imagePullPolicy: Always
        # --- ADDED FOR HPA BONUS ---
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # ---------------------------
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBHOST
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DBPWD
        - name: GROUP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GROUP_NAME
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: S3_IMAGE_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_IMAGE_KEY
        - name: AWS_REGION
          value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 81
  type: LoadBalancer